@startuml


class DataDisplay {
    DataStore dataStore
}

interface DataStore {
    read(fromPath)
    save(toPath)
}

class FileStore {
    read(fromPath)
    save(toPath)
}

class HttpStore {
    read(fromPath)
    save(toPath)
}

DataStore *-right- DataDisplay
DataStore <|-- FileStore
DataStore <|-- HttpStore


@enduml